/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE = 5;
  /** RegularExpression Id. */
  int NAME = 6;
  /** RegularExpression Id. */
  int ROBOTSKIP = 7;
  /** RegularExpression Id. */
  int TURN = 8;
  /** RegularExpression Id. */
  int FACE = 9;
  /** RegularExpression Id. */
  int PUT = 10;
  /** RegularExpression Id. */
  int PICK = 11;
  /** RegularExpression Id. */
  int MOVEDIR = 12;
  /** RegularExpression Id. */
  int RUNDIRS = 13;
  /** RegularExpression Id. */
  int MOVEFACE = 14;
  /** RegularExpression Id. */
  int NULL = 15;
  /** RegularExpression Id. */
  int BALLOONS = 16;
  /** RegularExpression Id. */
  int CHIPS = 17;
  /** RegularExpression Id. */
  int DIRECTION = 18;
  /** RegularExpression Id. */
  int CARDINALPOINT = 19;
  /** RegularExpression Id. */
  int CONSTANT = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int LOOP = 22;
  /** RegularExpression Id. */
  int REPEAT = 23;
  /** RegularExpression Id. */
  int FACING = 24;
  /** RegularExpression Id. */
  int BLOCKED = 25;
  /** RegularExpression Id. */
  int CANPUT = 26;
  /** RegularExpression Id. */
  int CANPICK = 27;
  /** RegularExpression Id. */
  int CANMOVE = 28;
  /** RegularExpression Id. */
  int ISZERO = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int NUM = 31;
  /** RegularExpression Id. */
  int EQUALS = 32;
  /** RegularExpression Id. */
  int LPAREN = 33;
  /** RegularExpression Id. */
  int RPAREN = 34;
  /** RegularExpression Id. */
  int DEFVAR = 35;
  /** RegularExpression Id. */
  int DEFUN = 36;
  /** RegularExpression Id. */
  int WORD = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"move\"",
    "\"name\"",
    "\"skip\"",
    "\"turn\"",
    "\"face\"",
    "\"put\"",
    "\"pick\"",
    "\"move-dir\"",
    "\"run-dirs\"",
    "\"move-face\"",
    "\"null\"",
    "\"ballons\"",
    "\"chips\"",
    "<DIRECTION>",
    "<CARDINALPOINT>",
    "<CONSTANT>",
    "\"if\"",
    "\"loop\"",
    "\"repeat\"",
    "\"facing?\"",
    "\"blocked?\"",
    "\"can-put?\"",
    "\"can-pick?\"",
    "\"can-move?\"",
    "\"isZero?\"",
    "\"not\"",
    "<NUM>",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"defvar\"",
    "\"defun\"",
    "<WORD>",
    "<DIGIT>",
  };

}
